export const newsArticles = [

  {
  id: 0,
  date: 'Mar 9, 2026',
  category: 'Official Statement',
  title: "Breathing But Not Competing: Nigeria's Opposition and the Road to 2027",
  excerpt:
    "As 2027 approaches, the opposition remains fragmented by personal ambitions, media theatrics, and a glaring absence of policy-driven platforms — raising serious questions about democratic competitiveness.",
  fullContent: {
    author: 'Mogaji (Hon) Seye Oladejo',
    role: 'Lagos APC Spokesman',
    date: '09/03/26',
    paragraphs: [
      "As the nation gradually approaches the 2027 general elections, it is becoming increasingly evident that Nigeria may be heading toward one of the most predictable electoral cycles in its democratic history. The reason is not far-fetched: an opposition that has repeatedly demonstrated a lack of coherence, courage, and constructive engagement with the pressing needs of the Nigerian people.",
      "The Lagos State chapter of the All Progressives Congress (APC) observes with concern how parties that should ordinarily provide credible alternatives have instead chosen the path of internal division, populist rhetoric, and political opportunism. Rather than building strong institutions, developing policy-driven platforms, or offering meaningful solutions to Nigeria's economic and social challenges, the opposition has largely confined itself to media theatrics and perpetual complaints.",
      "What is most evident today is a war within the opposition ranks, driven largely by unbridled personal ambition that is clearly at variance with present political realities. Instead of building consensus and strengthening party structures, leading figures within the opposition appear locked in a relentless contest of individual aspirations. The result is a fragmented and distracted political bloc unable to present a coherent national alternative.",
      "There is, in truth, very little on ground to suggest any meaningful preparedness for elections on the part of the opposition. Beyond occasional blabbing meant only to remind the public that they are still politically breathing, Nigerians have seen little evidence of organization, mobilization, or policy articulation that would normally precede a serious electoral contest. Unfortunately, it appears that this pattern may remain largely unchanged in the months ahead.",
      "We opine that it remains unhealthy for Nigeria's democratic growth if the opposition continues to remain inept, confused, and disunited. Democracy functions best when there is a responsible and organized opposition capable of presenting viable alternatives to the electorate. Unfortunately, the current situation reflects the opposite.",
      "Indeed, we do not require the gift of prophecy to recognize that an opposition in which virtually all major leaders are driven primarily by presidential ambitions is one that is inevitably headed for dysfunction. When personal ambitions eclipse collective strategy and national interest, political organizations inevitably weaken from within.",
      "In contrast, the APC at both the federal and state levels continues to demonstrate a commitment to governance, reforms, and national development. From economic restructuring initiatives to infrastructural investments and social interventions, our party remains focused on delivering results and strengthening democratic institutions.",
      "It is therefore unsurprising that as 2027 draws closer, Nigerians are increasingly looking toward continuity, stability, and proven leadership. Elections should be competitive and inspiring, but when those who claim to be alternatives fail to present credible visions or organized structures, the outcome naturally becomes more predictable.",
      "The Lagos APC encourages all political actors to elevate the standard of democratic engagement. Nigerians deserve robust debates, thoughtful policy proposals, and disciplined political organizations — not fragmented alliances driven by desperation rather than conviction.",
      "Our party remains confident that Nigerians will once again evaluate performance, leadership, and vision when the time comes. Until then, we remain committed to governance, service, and the continued progress of our great nation.",
    ],
  },
},
{
  id: 1,
  date: 'Mar 11, 2025',
  category: 'Official Statement',
  title: "Middle East Crisis Could Set Back Nigeria's Economic Gains",
  excerpt:
    "The Lagos APC warns that the evolving Middle East conflict poses real risks to Nigeria's macroeconomic recovery, citing potential disruptions to energy markets, exchange rate stability, and investor confidence.",
  fullContent: {
    author: 'Mogaji (Hon.) Seye Oladejo',
    role: 'Lagos APC Spokesman',
    date: '11/03/2025',
    paragraphs: [
      "The Lagos State Chapter of the All Progressives Congress (APC) is concerned about the evolving crisis in the Middle East and the potential implications for Nigeria's economic stability and recovery.",
      "The Lagos APC notes that the Middle East conflict, though external to Nigeria, has the potential to negatively affect our economic recovery and may constitute a setback to some of the recent macroeconomic gains.",
      "We have been closely observing the unfolding developments in the Middle East and the broader implications they hold for global stability and economic recovery across many nations, including Nigeria.",
      "While the situation continues to evolve, it is important to acknowledge that the ongoing conflict unfortunately poses a negative impact on Nigeria's economic recovery efforts. The instability in a region that plays a central role in global energy supply and international trade has created fresh uncertainties in global markets, affecting commodity prices, investment flows, and overall financial stability.",
      "For Nigeria, which has only recently begun to record encouraging signs of macroeconomic stabilization, the crisis represents a significant external shock and a potential setback to some of the gains recorded in recent months. Disruptions in global supply chains, volatility in energy markets, and rising costs in international trade may place additional pressure on inflation, exchange rate stability, and fiscal planning.",
      "Although fluctuations in global crude oil prices may present short-term revenue opportunities for oil-producing nations, such gains are often offset by broader economic pressures including higher import costs, global inflationary trends, and increased uncertainty for investors. These realities underline the complex nature of the global economic environment and the need for cautious and strategic policy responses.",
      "The Lagos APC therefore emphasizes the importance of careful economic management and proactive policy measures to mitigate the potential impact of these external shocks. Continued efforts toward economic diversification, strengthening domestic production, fiscal discipline, and structural reforms remain vital in building Nigeria's resilience against global crises beyond our control.",
      "We commend the Federal Government for its ongoing efforts to stabilize the economy and implement reforms aimed at restoring investor confidence and improving fiscal sustainability. We also take pride in the sound judgment and strategic direction demonstrated by the government's economic management team in navigating the complex challenges confronting the nation. Equally commendable is the patriotic resilience and enduring optimism of the Nigerian people, whose perseverance continues to support the country's ongoing reform and recovery process.",
      "We further call on the understanding and support of the general public, the private sector, and all relevant stakeholders as the Federal Government implements measures to absorb and ameliorate the effects of this unforeseen global development. Collective patience, cooperation, and commitment from all Nigerians will be crucial in ensuring that the nation navigates these challenges effectively while sustaining the momentum of economic recovery.",
      "At the same time, we urge the international community to intensify diplomatic engagements aimed at de-escalating tensions in the Middle East, as global peace and stability remain indispensable for sustained economic growth and development.",
      "The All Progressives Congress, Lagos State Chapter, remains committed to supporting policies and initiatives that protect Nigeria's economic interests, strengthen national resilience, and ensure that temporary global disruptions do not derail the nation's long-term path toward sustainable growth and prosperity.",
      "Nigeria has overcome global shocks in the past, and with prudent leadership, unity of purpose, and sound economic management, we remain confident that the country will continue to navigate these challenges successfully.",
    ],
  },
},


  {
    id: 2,
    date: 'Mar 7, 2026',
    category: 'Official Statement',
    title: 'From e-Registration to Congresses: Lagos APC Sets the Benchmark in Democratic Excellence',
    excerpt: 'The Lagos State Chapter of the APC has once again demonstrated why it remains the undisputed standard-bearer of party organization and democratic discipline in Nigeria.',
    fullContent: {
      author: 'Mogaji (Hon) Seye Oladejo',
      role: 'Lagos APC Spokesman',
      date: '07/03/2026',
      paragraphs: [
        'The Lagos State Chapter of the All Progressives Congress (APC) has once again demonstrated why it remains the undisputed standard-bearer of party organization and democratic discipline in Nigeria.',
        'From the resounding success of our electronic membership registration exercise to the seamless conduct of our Party Congresses, the APC has proven that structure, innovation, and order are not mere slogans — they are our culture.',
        'While others trade in confusion and press statements, we build systems. While others quarrel over factions, we strengthen institutions. While others manufacture propaganda, we consolidate progress.',
        'Across wards and local governments in Lagos State, our Congresses were conducted peacefully, transparently, and in strict compliance with constitutional guidelines. Participation was massive. The process was orderly. The outcome was clear: a united and forward-looking party ready for the tasks ahead.',
        'Beyond the successful conduct of the Congresses, the quality of members elected into the State Executive of the Party speaks volumes. The new leadership embodies a rare and strategic blend of experience and youthfulness, continuity and renewal, as well as deliberate gender balancing. It is a team forged from institutional memory and fresh energy — a combination designed not just to sustain progress, but to accelerate it.',
        'It is time for opposition parties to dismount from their high horses and enroll in the elementary school of politics where discipline, cohesion, organization, and unity of purpose are taught. Politics is not noise-making. It is not social media agitation. It is not perpetual internal crisis. It is structure. It is coordination. It is leadership.',
        'These enduring values remain the bedrock of the progressive movement\'s dominance in Lagos State and across Nigeria. They explain why the APC continues to grow stronger while others grow louder — and weaker.',
        'Above all, this moment once again affirms the absolute trust that Lagosians place in the APC as a serious, competent, and result-driven political platform worthy of their mandate. The people of Lagos have consistently chosen stability over chaos, progress over bitterness, and performance over empty rhetoric.',
        'We will not be distracted by noise. We will not be slowed by cynicism. And we will certainly not take lectures on organization from parties that cannot organize themselves.',
        'The APC in Lagos stands disciplined. It stands cohesive. It stands battle-ready. And when the time comes, the verdict of the people will once again be emphatic.',
      ],
    },
  },
  {
    id: 3,
    date: 'Mar 4, 2026',
    category: 'Obituary',
    title: 'Lagos APC Mourns the Sudden Passing of Hon. Karamo Yesiro',
    excerpt: 'The Lagos State Chapter of the APC received with profound shock and deep sorrow the news of the sudden demise of our newly elected Assistant Publicity Secretary, Hon. Karamo Yesiro.',
    fullContent: {
      author: 'Mogaji (Hon) Seye Oladejo',
      role: 'Lagos APC Spokesman',
      date: '04/03/26',
      paragraphs: [
        'The Lagos State Chapter of the All Progressives Congress (APC) received with profound shock and deep sorrow the news of the sudden demise of our newly elected Assistant Publicity Secretary, Hon. Karamo Yesiro.',
        'Hon. Yesiro\'s passing is a painful and tragic loss to our great party at a time when his energy, commitment, and passion for progressive politics were most needed. Having just been entrusted with the responsibility of serving in the State Executive Council, he embodied dedication, loyalty, and an unwavering belief in the ideals of our party.',
        'Though his tenure was tragically cut short, his enthusiasm, humility, and readiness to serve left a lasting impression on colleagues and members alike. He was a vibrant party man whose contributions to the growth and stability of the APC in Lagos State will not be forgotten.',
        'On behalf of the leadership and entire membership of the Lagos APC, we extend our heartfelt condolences to his immediate family, political associates, friends, and supporters during this difficult time. We pray that Almighty God grants his family the strength to bear this irreparable loss and grants his soul eternal rest.',
        'The Lagos APC stands united in mourning this painful departure. Hon. Karamo Yesiro will be remembered for his service, commitment, and belief in the progressive cause.',
        'May his soul rest in perfect peace.',
      ],
    },
  },
  {
    id: 4,
    date: 'Mar 4, 2026',
    category: 'Official Statement',
    title: 'Lagos APC Debunks False Report on SLG Recall',
    excerpt: 'The Lagos State APC has categorically denied reports claiming the State Chairman recalled all SLGs and supervisors to Acme in connection with alleged Villa directives.',
    fullContent: {
      author: 'Mogaji (Hon) Seye Oladejo',
      role: 'Lagos APC Spokesman',
      date: '04/03/26',
      paragraphs: [
        'The Lagos State Chapter of the All Progressives Congress (APC) has been made aware of reports claiming that the State Chairman has recalled all SLGs and supervisors to Acme in connection with directives allegedly issued at the Villa.',
        'We wish to categorically state that this report is false, misleading, and clearly intended to create unnecessary tension within our party and among the public.',
        'At no time did the State Chairman issue any such directive, nor is there any emergency meeting scheduled as being speculated. The Lagos APC remains a disciplined, transparent, and law-abiding political party, guided strictly by due process and collective decision-making.',
        'Our primary focus at this critical time remains putting every necessary structure in place as we count down to the forthcoming national elections. We are fully committed to strengthening our internal processes and mobilizing effectively to ensure continued progress and victory at the polls.',
        'We therefore advise party members, supporters, and the general public to desist from spreading or entertaining rumors capable of needlessly heating up the polity. The party will continue to keep the public informed of any official updates through our usual and recognized communication channels.',
      ],
    },
  },
  {
    id: 5,
    date: 'Feb 10, 2026',
    category: 'Mobilization',
    title: 'Ojelabi Urges Unity at Lagos East Mega Rally',
    excerpt: "Lagos APC Chairman, Pastor Cornelius Ojelabi, calls for internal cohesion and grassroots mobilization to consolidate the party's achievements ahead of 2027.",
    fullContent: {
      author: 'Lagos APC Media Unit',
      role: 'Official Press Release',
      date: '10/02/26',
      paragraphs: [
        'Lagos APC Chairman, Pastor Cornelius Ojelabi, delivered a powerful address at the Lagos East Mega Rally, calling on all party members to close ranks and present a united front ahead of the 2027 general elections.',
        "Speaking before thousands of APC faithful gathered at the rally grounds, the Chairman emphasized that the party's greatest strength lies in its unity and its deep roots in every ward across Lagos State.",
        '"Our party is built on a foundation of service, discipline, and shared vision. The time for division is over — the time for victory is now," Chairman Ojelabi declared to thunderous applause.',
        'He also commended ward and local government leaders for their dedication to the Renewed Hope agenda, and urged all members to intensify voter mobilization in their respective areas.',
        "The rally, which drew participants from all 20 LGAs, was a testament to the party's organizational strength and its readiness to deliver results in the upcoming electoral cycle.",
      ],
    },
  },
  {
    id: 6,
    date: 'Feb 5, 2026',
    category: 'Registration',
    title: 'Lagos Leads in Nationwide APC E-Registration',
    excerpt: 'The Chairman commends the Ikorodu division for record-breaking numbers in the ongoing digital party membership enrollment drive.',
    fullContent: {
      author: 'Lagos APC Secretariat',
      role: 'Official Statement',
      date: '05/02/26',
      paragraphs: [
        'Lagos State has emerged as the leading chapter in the All Progressives Congress nationwide digital membership enrollment exercise, with the Ikorodu division recording the highest numbers in the ongoing e-registration drive.',
        "State Chairman Pastor Cornelius Ojelabi praised the remarkable achievement, noting that Lagos's performance reflects the party's deep grassroots penetration and the enthusiasm of Lagosians to participate in the democratic process.",
        'The e-registration exercise leverages a new digital platform developed by the national party secretariat, allowing members to update their details, register new members, and obtain digital party cards.',
        'Over 250,000 new and returning members have been enrolled in Lagos State alone in the first two weeks of the exercise. The Ikorodu, Alimosho, and Ikeja divisions have been recognized as top performers.',
        'Chairman Ojelabi urged all LGA chairmen and ward coordinators to sustain the momentum and ensure that every APC member in Lagos is captured in the new digital register before the deadline.',
      ],
    },
  },
];